---
# Install java packages on redhat based distributions.

- name: Install EPEL.
  yum: name=epel-release state=present

- name: Install the openjdk 1.8 package.
  yum: name=java-1.8.0-openjdk-headless.x86_64 state=installed
